In [55]:
%pylab nbagg

Populating the interactive namespace from numpy and matplotlib


C:\Users\celie\OneDrive\Documenten\TVB_Windows_2.2\TVB_Distribution\tvb_data\Lib\site-packages\IPython\core\magics\pylab.py:160: UserWarning: pylab import has clobbered these variables: ['fft', 'f', 'ifft']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [56]:
from tvb.simulator.lab import *
import h5py
import os
import matplotlib.pyplot as plt

import scipy 
import scipy.fftpack
import seaborn as sns

import scipy 
import scipy.fftpack
from scipy.fft import fft, ifft
from scipy import signal
from scipy.integrate import simps
from fooof import FOOOF
from scipy import stats

import pandas as pd
from statistics import stdev

In [ ]:
import statistics
from rpy2.robjects.packages import importr
from rpy2.robjects.vectors import FloatVector

stats2 = importr('stats')
def EFsize(c0, c1):
    d = (mean(c0) - mean(c1)) / (sqrt((statistics.stdev(c0) ** 2 + statistics.stdev(c1) ** 2) / 2))
    return d

In [57]:
os.chdir("C:/Users/celie/OneDrive - ugentbe/NOG NODIG/2de master/Masterproef/Wilson Cowan/DATA")

In [58]:
#import connectivity file to know which region corresponds to which index in the matrices
filename = "Connectivity.h5"

with h5py.File(filename, "r") as f:
    # List all groups
    print("Keys: %s" % f.keys())
    a_group_key = list(f.keys())[0]

    # Get the data
    regions_list = list(f['region_labels'])

regions = np.array(regions_list)

Keys: <KeysViewHDF5 ['areas', 'centres', 'cortical', 'hemispheres', 'orientations', 'region_labels', 'tract_lengths', 'weights']>


In [82]:
mydir = "C:/Users/celie/OneDrive - ugentbe/NOG NODIG/2de master/Masterproef/Datasets/All_freqs/Peak"

filename = mydir + "/health_alpha_left_peaks.h5"
with h5py.File(filename, "r") as f:
    health_left = f["data"]
    health_left = np.array(health_left)
    
filename = mydir + "/health_alpha_right_peaks.h5"
with h5py.File(filename, "r") as f:
    health_right = f["data"]
    health_right = np.array(health_right)
    
filename = mydir + "/depr_alpha_left_peaks.h5"
with h5py.File(filename, "r") as f:
    depr_left = f["data"]
    depr_left = np.array(depr_left)
    
filename = mydir + "/health_alpha_right_peaks.h5"
with h5py.File(filename, "r") as f:
    depr_right = f["data"]
    depr_right = np.array(depr_right)

In [94]:
print(health_left)
print(health_right)
print(depr_left)
print(depr_right)

[10.55769332 10.55769332 10.55769332  9.761118  ]
[11.93009709 11.93009709 11.93009709  8.45048544]
[10.5526557  10.5526557  10.5526557   9.76280701]
[[11.93009709 11.93009709 11.93009709  8.45048544]]


In [90]:
health_left= health_left[~numpy.isnan(health_left)]
health_right= health_right[~numpy.isnan(health_right)]
depr_left= depr_left[~numpy.isnan(depr_left)]
depr_left= depr_left[~numpy.isnan(depr_left)]

In [91]:
test = stats.ttest_ind(health_left, health_right).pvalue
test2 = stats.ttest_ind(health_left, health_right).pvalue

In [93]:
print(test)
print(test2)

0.4616410881182924
0.4616410881182924
